const root_path = "./facebook/";

const models = [
  {
    id: 1,
    category: 0,
    city: "Maputo",
    gender: "F",
    class_age: 1,
    pic: root_path + "1.jpg",
    average_price_pic: 30,
  },
  {
    id: 2,
    category: 0,
    city: "Maputo",
    gender: "F",
    class_age: 1,
    pic: root_path + "2.jpg",
    average_price_pic: 30,
  },
  {
    id: 3,
    category: 0,
    city: "Gaza",
    gender: "M",
    class_age: 1,
    pic: root_path + "3.jpg",
    average_price_pic: 30,
  },
  {
    id: 4,
    category: 0,
    city: "Maputo",
    gender: "F",
    class_age: 1,
    pic: root_path + "4.jpg",
    average_price_pic: 30,
  },
  {
    id: 5,
    category: 0,
    city: "Niassa",
    gender: "F",
    class_age: 1,
    pic: root_path + "5.jpg",
    average_price_pic: 30,
  },
  {
    id: 6,
    category: 0,
    city: "Maputo",
    gender: "M",
    class_age: 1,
    pic: root_path + "1.jpg",
    average_price_pic: 30,
  },
  {
    id: 7,
    category: 0,
    city: "Maputo",
    gender: "F",
    class_age: 1,
    pic: root_path + "7.jpg",
    average_price_pic: 30,
  },
  {
    id: 8,
    category: 0,
    city: "Niassa",
    gender: "M",
    class_age: 1,
    pic: root_path + "8.jpg",
    average_price_pic: 30,
  },
  {
    id: 9,
    category: 0,
    city: "Maputo",
    gender: "F",
    class_age: 1,
    pic: root_path + "9.jpg",
    average_price_pic: 30,
  },
  {
    id: 10,
    category: 0,
    city: "Sofala",
    gender: "M",
    class_age: 1,
    pic: root_path + "10.jpg",
    average_price_pic: 30,
  },
  {
    id: 11,
    category: 0,
    city: "Maputo",
    gender: "M",
    class_age: 1,
    pic: root_path + "11.jpg",
    average_price_pic: 30,
  },
  {
    id: 12,
    category: 0,
    city: "Maputo",
    gender: "F",
    class_age: 1,
    pic: root_path + "12.jpg",
    average_price_pic: 30,
  },
  {
    id: 13,
    category: 0,
    city: "Maputo",
    gender: "F",
    class_age: 1,
    pic: root_path + "13.jpg",
    average_price_pic: 30,
  },
  {
    id: 14,
    category: 0,
    city: "Tete",
    gender: "F",
    class_age: 1,
    pic: root_path + "14.jpg",
    average_price_pic: 30,
  },
  {
    id: 15,
    category: 0,
    city: "Cabo delgado",
    gender: "F",
    class_age: 1,
    pic: root_path + "1.jpg",
    average_price_pic: 30,
  },
  {
    id: 16,
    category: 0,
    city: "Maputo",
    gender: "F",
    class_age: 1,
    pic: root_path + "9.jpg",
    average_price_pic: 30,
  },
];

export default models;
